#!/bin/bash

# Logo Download Helper Script
# This script helps you download company logos to the correct directory

LOGO_DIR="/Users/namanshukla/Downloads/CODING/90toZero/frontend/public/images/logos/companies"

echo "🚀 90toZero Logo Download Helper"
echo "================================"
echo ""
echo "Company logos should be saved to: $LOGO_DIR"
echo ""
echo "📋 Required logos (save as PNG with transparent background):"
echo ""
echo "Indian IT Companies:"
echo "  - tcs.png        → Download from https://www.tcs.com or Google Image Search"
echo "  - infosys.png    → Download from https://www.infosys.com"
echo "  - wipro.png      → Download from https://www.wipro.com"
echo ""
echo "Global Tech:"
echo "  - amazon.png     → Download from https://www.amazon.jobs or press kit"
echo "  - google.png     → Download from https://about.google/brand-resource-center/"
echo "  - microsoft.png  → Download from Microsoft brand resources"
echo "  - flipkart.png   → Download from https://www.flipkart.com"
echo ""
echo "Consulting Firms:"
echo "  - accenture.png  → Download from https://www.accenture.com"
echo "  - deloitte.png   → Download from https://www2.deloitte.com"
echo "  - kpmg.png       → Download from https://home.kpmg"
echo "  - ey.png         → Download from https://www.ey.com"
echo "  - pwc.png        → Download from https://www.pwc.com"
echo ""
echo "Indian Startups:"
echo "  - paytm.png      → Download from https://paytm.com"
echo "  - zomato.png     → Download from https://www.zomato.com"
echo "  - swiggy.png     → Download from https://www.swiggy.com"
echo ""
echo "🎨 Logo Specifications:"
echo "  - Format: PNG with transparent background"
echo "  - Recommended size: 200x60px (or similar 3:1 aspect ratio)"
echo "  - File size: < 50KB for web optimization"
echo "  - Color: Use official brand colors or grayscale-friendly versions"
echo ""
echo "💡 Alternative: Use free logo resources like:"
echo "  - https://www.brandfetch.com/"
echo "  - https://worldvectorlogo.com/"
echo "  - https://logodownload.org/"
echo ""
echo "📁 After downloading, place all logos in:"
echo "   $LOGO_DIR"
echo ""
echo "🔄 The website will automatically show logos once they're in place."
echo "   Text fallbacks are already configured for missing logos."
echo ""
